name: Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Zola
        run: sudo snap install zola --edge
      - name: Build Project
        run: zola build
      - name: Deploy to Production
        run: |
          npx netlify deploy \
            --prod \
            --dir ./public \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}
